<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.AspNetCore" Version="2.*" />
    <PackageReference Include="Grpc.AspNetCore.Web" Version="2.*" />
    <PackageReference Include="HotChocolate.AspNetCore" Version="13.*" />
    <PackageReference Include="HotChocolate.AspNetCore.Authorization" Version="13.*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="SoapCore" Version="1.*" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Controllers\" />
    <Folder Include="Generated\" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="Grpc\Protos\weather.proto" GrpcServices="Server" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GithubIssuesIS.Application\GithubIssuesIS.Application.csproj" />
    <ProjectReference Include="..\DMS.Infrastrucure.GitHub\DMS.Infrastrucure.GitHub.csproj" />
    <ProjectReference Include="..\DMS.Infrastrucure.Import\DMS.Infrastrucure.Import.csproj" />
    <ProjectReference Include="..\DMS.Infrastrucure.JwtAuthorization\DMS.Infrastrucure.JwtAuthorization.csproj" />
    <ProjectReference Include="..\DMS.Infrastrucure.Weather\DMS.Infrastrucure.Weather.csproj" />
    <ProjectReference Include="..\GithubIssuesIS.Repository\GithubIssuesIS.Repository.csproj" />
  </ItemGroup>

</Project>
